# Generated by Django 3.1 on 2020-08-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_register',
            name='password1',
            field=models.CharField(default='SOME STRING', max_length=32),
        ),
        migrations.AddField(
            model_name='emp_register',
            name='password2',
            field=models.CharField(default='SOME STRING', max_length=32),
        ),
        migrations.AddField(
            model_name='emp_register',
            name='u_name',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_register',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emp_register',
            name='l_name',
            field=models.CharField(max_length=100),
        ),
    ]
