# Generated by Django 3.1 on 2020-08-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0002_auto_20200828_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(default='first name', max_length=100)),
                ('l_name', models.CharField(default='last name', max_length=100)),
                ('username', models.CharField(default='user name', max_length=100)),
                ('email', models.EmailField(default='email id', max_length=100)),
                ('password1', models.CharField(default='password', max_length=32)),
                ('password2', models.CharField(default='confirm password', max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp_register',
        ),
    ]
